version: '3'

services:
  ## PHP-Apache service
  server:
    build:
      context: ./application
    container_name: ai-shop-webserver
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./application/source:/var/www/html
    env_file:
      - ./docker.env
    networks:
      - ai-shop

  ## Mariadb service 
  database:
    image: mariadb:10.4.2
    container_name: ai-database
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - ai-data_data:/var/lib/mysql
    env_file:
      - ./docker.env
    networks:
      - ai-shop

  ## PhpMyAdmin
  myadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: ai-phpmyadmin
    ports:
      - 8081:80
    restart: always
    env_file:
      - ./docker.env
    depends_on:
      - database
    networks:
      - ai-shop
networks:
  ai-shop:

volumes:
  ai-data_data:
